spring:
  application:
    name: codinghub-web
  datasource:
    url: jdbc:mysql://localhost:3306/codinghub?useSSL=false&serverTimezone=UTC
    username: root
    password: hsc0423
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080